### ISSUE TITLE
Is there any plan about storing logs in localStorage

### ISSUE THREAD

**Issue by jonathan-chancetop** [dionshihk/core-native-project#11]
Is there any plan about storing logs in localStorage? Since we just store logs in memory, if there is a crash, or user force exit app, the logs will lost, should we storage logs in localStorage and load them when app start to prevent logs lost?

**Comment by lokshunhung** [comment]
Probably not, [logs are periodically sent to server](https://github.com/dionshihk/core-native-project/blob/580b6e83851c6ebc3df52764e9043c0c71a8f88d/src/Logger.ts#L31-L32)

**Comment by neowu** [comment]
we don't see event log as critical message, and we also drop entire logs if anything wrong, to prevent consume too much ram,

for crash report, it's definitely something else should handle it, event logs is only on application level

for event logs, i guess what we could do is to trigger sendEventLogs if user close/switch out the app (e.g. the state of root component become to inactive), to try to send event log as much as possible

@dionshihk  what do you think ?

**Comment by neowu** [comment]
it looks like no simple way to handle RN close/switch to background event? if that adds too much complexity, i would think not worth just to send little more event logs, 
(especially if there is error, we trigger sendEventLogs immediately)

**Comment by lokshunhung** [comment]
Triggering sendEventLogs during app foreground/background changes if done on JS (eg [using this](https://github.com/amrlabib/react-native-appstate-hook)) is still application level, and may fail to report logs when app is force closed by native code since communication through JS bridge is asynchronous. I'm not sure if there are existing packages in the react native ecosystem that handles event logging natively, such that exceptions on native side can be handled synchronously.

**Comment by neowu** [comment]
if it's simple AppState add/remove listener, then it probably worth to do it, and we don't need to target 100% cases, it's good enough to send log as much as possible (to keep the cost of sending log low)

from the doc, only iOS supports inactive state
https://reactnative.dev/docs/appstate#app-states

**Comment by jonathan-chancetop** [comment]
Yes, we don't need to track crash event since we can do this by using other native libraries such as bugsnag.
I think listening to app state change is a good idea, by this we can avoid losing any logs.

**Comment by dionshihk** [comment]
Agree with @neowu @lokshunhung 's answers.

From one side, sending logs to target server is a better-do not a must-do, and some log loss (of low proportion) is acceptable. So, there is no plan to store every log into device storage for next-time resend.

On the other side, I just added `immediately send logs when app becomes inactive` feature in `2.6.1`.

This feature is useful for iOS, because iOS has lots of limitations for background execution. 
While for Android, the timer (for sending logs) is still running even if the app is in background.

The commit is quite simple, check out here:
https://github.com/dionshihk/core-native-project/commit/d7d06a63c59314032b615461a5fe8159595acad2#diff-c830d9785316a9bc5fae002cd2a9adba68ddc16515413eb054529e9255947c3c

Thank you all for the suggestion.

**Comment by jonathan-chancetop** [comment]
Ok, thanks. That makes sense.
