### ISSUE TITLE
Handle errorMessage in Logger

### ISSUE THREAD

**Issue by jonathan-chancetop** [dionshihk/core-native-project#12]
After we upgrade to the latest core-native, there is an exception occurred many times, and after we investigated, we found that it is because this condition:
`"errorMessage" in entry ? entry.errorMessage.substr(0, 1000) : undefined`
while there is errorMessage defined in the log entry, even "null" and "undefined" would be treated as "true" in this code, is that our design purpose?

**Comment by dionshihk** [comment]
Simply speaking, when using this framework, we should follow the library's typing in TypeScript system.

Usually we do not perform extra runtime type checking, because we trust the user is not bypassing TypeScript check.

In interface `Log`, errorCode / errorMessage are required to be string, or not specified (undefined). 
(defined in `https://github.com/dionshihk/core-native-project/blob/master/src/Logger.ts`)

Therefore, passing `null` or explicit `undefined` actually breaks the interface definition, which may affect the runtime behavior.

Hope my answer can help you, thank you.

**Comment by jonathan-chancetop** [comment]
Ok，got it. We face this issue because there are some third party libraries that throw exception with message, but the message may be null while they are specified as not null. If this is our design's purpose, then I will find another way to make sure the message won't be null.
